spring.application.name=GenerarCita
server.port:8082

spring.datasource.url=jdbc:sqlserver://192.168.0.29:1433;databaseName=LOLCLI9000;encrypt=false
spring.datasource.username=applolcli
spring.datasource.password=Lolcliapp23
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.devtools.add-properties=false


file.upload-dir=C:/Users/Carlos/Documents/Bartolito/uploads

#file.upload-dir=uploads

spring.web.resources.static-locations=file:${file.upload-dir}/,classpath:/static/
spring.mvc.static-path-pattern=/images/**
